FOGL-2877: Initial implementation of DNP3 south plugin
foglamp/foglamp-south-dnp3 pull request #1
Opened 2019-07-03 16:13 UTC by pintomax

FOGL-2877: Initial implementation of DNP3 south plugin

Counter, Binary, BinaryOutputStatus and Analog objects are currettly supported.

2019-07-03 17:19 UTC, MarkRiddoch requested changes
Looks good on the whole

2019-07-03 17:19 UTC, MarkRiddoch commented on CMakeLists.txt
> +set(CMAKE_BUILD_TYPE "Debug")
We should not checkin with Debug set here

2019-07-03 17:19 UTC, MarkRiddoch commented on README.rst
> +    {"outstations":["IP_1:PORT_1:ID_1", "IP_2:PORT_2:ID_2"]}
Didn't you change this?

2019-07-03 17:19 UTC, MarkRiddoch commented on dnp3.cpp
> +		manager->AddTCPClient("tcpclient_1", // alias in log messages
Could we make this more descriptive than tcpclient_1? Name use the service name.

2019-07-03 17:19 UTC, MarkRiddoch commented on dnp3.cpp
> +	// you can optionally override these defaults likei:
typo likei

2019-07-03 17:19 UTC, MarkRiddoch commented on dnp3.cpp
> +	stackConfig.master.responseTimeout = TimeDuration::Seconds(5);
Maybe this should be a configuration option

2019-07-03 17:19 UTC, MarkRiddoch commented on dnp3.cpp
> +		if (flag == 0x01 ||
We should maybe create an enum or have a set of defines for the flag values

2019-07-03 17:19 UTC, MarkRiddoch commented on plugin.cpp
> +       		"description" : "Simple DNP3 data change plugin",
minor point - formatting

2019-07-03 17:19 UTC, MarkRiddoch commented on plugin.cpp
> +		"displayName" : "Asset Name prefix",
Display names appear in GUI so need to be short. Descriptions should be more descriptive than display names.

2019-07-03 17:19 UTC, MarkRiddoch commented on plugin.cpp
> +	"outstation_poll_interval" : {
I think it will be consign that we have two poll intervals defined.

2019-07-03 17:19 UTC, MarkRiddoch commented on plugin.cpp
> +void plugin_start(PLUGIN_HANDLE *handle)
This should be PLUGIN_HANDLE handle

2019-07-03 17:19 UTC, MarkRiddoch commented on plugin.cpp
> +void plugin_register_ingest(PLUGIN_HANDLE *handle, INGEST_CB cb, void *data)
Should be PLUGIN_HANDLE, not PLUGIN_HANDLE *

2019-07-03 17:19 UTC, MarkRiddoch commented on plugin.cpp
> +Reading plugin_poll(PLUGIN_HANDLE *handle)
PLUGIN_HANDLE not PLUGIN_HANDLE *

2019-07-03 17:19 UTC, MarkRiddoch commented on plugin.cpp
> +void plugin_shutdown(PLUGIN_HANDLE *handle)
PLUGIN_HANDLE not PLUGIN_HANDLE *

2019-07-03 17:19 UTC, MarkRiddoch commented on plugin.cpp
> +	DNP3* dnp3 = (DNP3 *)handle;
DNP3 *dnp = (DNP3 *)*handle

This is the one place it really is a PLUGIN_HANDLE * - at least until we fix that bug

2019-07-03 18:01 UTC, pintomax commented on README.rst
> +    {"outstations":["IP_1:PORT_1:ID_1", "IP_2:PORT_2:ID_2"]}
Yes, oversight

2019-07-04 08:05 UTC, pintomax commented on dnp3.cpp
> +		manager->AddTCPClient("tcpclient_1", // alias in log messages
Assuming service name is DNP3_ABC

the label is now: serviceName + _ + "remote_" + outstation id

DNP3_ABC_remote_20

2019-07-04 15:44 UTC, MarkRiddoch approved these changes

2019-07-04 16:15 UTC, merged