FOGL-2988 Add packaging files
foglamp/foglamp-south-dnp3 pull request #3
Opened 2019-07-08 13:18 UTC by MarkRiddoch

2019-07-08 13:25 UTC, ashish-jabble requested changes
Please add requirements for deb and rpm packager in Package file And add `foglamp.version` file as required for packaging.

2019-07-08 14:00 UTC, ashish-jabble commented
Also it is failing on ubuntu16.04 (- Configuring incomplete, errors occurred!). Below are the attached logs
[dnp3.txt](https://github.com/foglamp/foglamp-south-dnp3/files/3368689/dnp3.txt)
It may need require changes in requirements.sh

2019-07-08 15:35 UTC, MarkRiddoch commented
> Also it is failing on ubuntu16.04 (- Configuring incomplete, errors occurred!). Below are the attached logs
> [dnp3.txt](https://github.com/foglamp/foglamp-south-dnp3/files/3368689/dnp3.txt)
> It may need require changes in requirements.sh

I think we may be best to put the Ubuntu 16 issue in a separate Jira and get Massimiliano to look into it when he gets back.

2019-07-08 16:34 UTC, ashish-jabble commented
> I think we may be best to put the Ubuntu 16 issue in a separate Jira

Actually it is giving error on all the platforms. Should we exclude this plugin from CI packaging jobs for now or let them fail on CI?

2019-07-09 13:05 UTC, MarkRiddoch commented
Pushed some more changes that should now resolve this on Ubuntu 16 and 18. Also Raspbian, but not yet been able to test CentOS/RedHat platforms.

2019-07-10 09:09 UTC, ashish-jabble commented on Package
> +	deb)
Please add requirements which are needed for this plugin.

2019-07-11 13:02 UTC, ashish-jabble commented
@MarkRiddoch Except ub16, all fine on ub18 and Rpi.

2019-07-11 13:59 UTC, MarkRiddoch commented
The opendnp3 library does not compile on CentOS 7 currently. Therefore let's exclude this plugin from CentOS/RHEL for the time. A new Jira will be opened for support on that platform.

Could you tell me what you are seeing on Ubuntu 16 please? I see the package being generated without any reported problems.

2019-07-12 06:58 UTC, ashish-jabble approved these changes
It seems like something with my environment. Now all good.

2019-07-12 10:08 UTC, merged